blank_issues_enabled: false
contact_links:
  - name: Уязвимость или утечка данных / Vulnerability or privacy leak
    url: https://github.com/realfamousbae/Veil/security/advisories/new
    about: Сообщайте закрыто / Report privately
